module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "ambersecondarya-300": "var(--ambersecondarya-300)",
        "ambersecondarya-50": "var(--ambersecondarya-50)",
        "bright-blueprimaryb300": "var(--bright-blueprimaryb300)",
        "bright-blueprimaryb400": "var(--bright-blueprimaryb400)",
        "bright-blueprimaryb50": "var(--bright-blueprimaryb50)",
        "bright-blueprimaryb500": "var(--bright-blueprimaryb500)",
        "defaultgray-700": "var(--defaultgray-700)",
        "defaultgray-900": "var(--defaultgray-900)",
        defaultshadeblack: "var(--defaultshadeblack)",
        defaultshadewhite: "var(--defaultshadewhite)",
        "grayg-0": "var(--grayg-0)",
        "grayg-10": "var(--grayg-10)",
        "grayg-100": "var(--grayg-100)",
        "grayg-20": "var(--grayg-20)",
        "grayg-30": "var(--grayg-30)",
        "grayg-500": "var(--grayg-500)",
        "grayg-700": "var(--grayg-700)",
        "grayg-900": "var(--grayg-900)",
        neutralswhite: "var(--neutralswhite)",
        "primary-color-blueb50": "var(--primary-color-blueb50)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "desktop-body-medium": "var(--desktop-body-medium-font-family)",
        "desktop-body-regular": "var(--desktop-body-regular-font-family)",
        "desktop-h1-bold": "var(--desktop-h1-bold-font-family)",
        "desktop-h3-bold": "var(--desktop-h3-bold-font-family)",
        "desktop-h3-semibold": "var(--desktop-h3-semibold-font-family)",
        "desktop-h4-bold": "var(--desktop-h4-bold-font-family)",
        "desktop-h6-bold": "var(--desktop-h6-bold-font-family)",
        "desktop-h6-semibold": "var(--desktop-h6-semibold-font-family)",
        "desktop-small-medium": "var(--desktop-small-medium-font-family)",
        "desktop-small-regular": "var(--desktop-small-regular-font-family)",
        "desktop-small-semibold": "var(--desktop-small-semibold-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
